name: kelasdigital
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.6
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  equatable: ^2.0.5
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  introduction_screen: ^3.1.12
  jwt_decoder: ^2.0.1
  lottie: ^3.1.0
  package_info_plus: ^5.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  slide_countdown: ^1.5.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/flags/
    - assets/images/logos/
    - assets/images/onboards/
    - assets/images/icons/
    - assets/images/icons/register/
    - assets/images/profiles/
    - assets/svgs/
    - assets/animations/
    
  uses-material-design: true
